package Paastel.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class File_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode fileComponent : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.fileComponents$qwmK))) {
      if (SNodeOperations.isInstanceOf(fileComponent, CONCEPTS.Solution$gn)) {
        SNode solution = ((SNode) fileComponent);
        if (SEnumOperations.isMember(SPropertyOperations.getEnum(solution, PROPS.copyOption$5yWd), 0x4e183cf3aee61ad2L)) {
          continue;
        }
        if (SEnumOperations.isMember(SPropertyOperations.getEnum(solution, PROPS.copyOption$5yWd), 0x4e183cf3aee61ad3L)) {
          for (SNode item : SLinkOperations.getChildren(SLinkOperations.getTarget(solution, LINKS.replacement$hs8K), LINKS.linesOfText$zc_R)) {
            tgs.appendNode(item);
          }
        }
        if (SEnumOperations.isMember(SPropertyOperations.getEnum(solution, PROPS.copyOption$5yWd), 0x4e183cf3aee61ad6L)) {
          for (SNode item : SLinkOperations.getChildren(solution, LINKS.linesOfText$Smbh)) {
            tgs.appendNode(item);
          }
        }
      }
      if (SNodeOperations.isInstanceOf(fileComponent, CONCEPTS.Text$5c)) {
        SNode text = ((SNode) fileComponent);
        tgs.appendNode(text);
      }

    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty copyOption$5yWd = MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L, 0x4e183cf3aee61adeL, "copyOption");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink replacement$hs8K = MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L, 0x4e183cf3aef7fa26L, "replacement");
    /*package*/ static final SContainmentLink linesOfText$zc_R = MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee80213L, 0x4e183cf3aee80216L, "linesOfText");
    /*package*/ static final SContainmentLink linesOfText$Smbh = MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L, 0x4e183cf3aedc8595L, "linesOfText");
    /*package*/ static final SContainmentLink fileComponents$qwmK = MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, 0x6ff78d4ba1740029L, "fileComponents");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Solution$gn = MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L, "Paastel.structure.Solution");
    /*package*/ static final SConcept Text$5c = MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL, "Paastel.structure.Text");
  }
}
