package Paastel.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Text_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$f9B0));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty text$f9B0 = MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL, 0x6ff78d4ba174002eL, "text");
  }
}
