package Paastel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CopyOption extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CopyOption() {
    super(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee61ad1L, "CopyOption", "r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708469969");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_REMOVED_0 = new EnumerationDescriptor.MemberDescriptor("REMOVED", "REMOVED", 0x4e183cf3aee61ad2L, "r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708469970");
  private final EnumerationDescriptor.MemberDescriptor myMember_REPLACED_0 = new EnumerationDescriptor.MemberDescriptor("REPLACED", "REPLACED", 0x4e183cf3aee61ad3L, "r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708469971");
  private final EnumerationDescriptor.MemberDescriptor myMember_KEPT_0 = new EnumerationDescriptor.MemberDescriptor("KEPT", "KEPT", 0x4e183cf3aee61ad6L, "r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708469974");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee61ad1L, 0x4e183cf3aee61ad2L, 0x4e183cf3aee61ad3L, 0x4e183cf3aee61ad6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_REMOVED_0, myMember_REPLACED_0, myMember_KEPT_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "REMOVED":
        return myMember_REMOVED_0;
      case "REPLACED":
        return myMember_REPLACED_0;
      case "KEPT":
        return myMember_KEPT_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
