package Paastel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFile = createDescriptorForFile();
  /*package*/ final ConceptDescriptor myConceptIFileComponent = createDescriptorForIFileComponent();
  /*package*/ final ConceptDescriptor myConceptSolution = createDescriptorForSolution();
  /*package*/ final ConceptDescriptor myConceptSolutionReplacement = createDescriptorForSolutionReplacement();
  /*package*/ final ConceptDescriptor myConceptSolutionReplacementStart = createDescriptorForSolutionReplacementStart();
  /*package*/ final ConceptDescriptor myConceptSolutionStart = createDescriptorForSolutionStart();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  /*package*/ final EnumerationDescriptor myEnumerationCopyOption = new EnumerationDescriptor_CopyOption();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFile, myConceptIFileComponent, myConceptSolution, myConceptSolutionReplacement, myConceptSolutionReplacementStart, myConceptSolutionStart, myConceptText);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.File:
        return myConceptFile;
      case LanguageConceptSwitch.IFileComponent:
        return myConceptIFileComponent;
      case LanguageConceptSwitch.Solution:
        return myConceptSolution;
      case LanguageConceptSwitch.SolutionReplacement:
        return myConceptSolutionReplacement;
      case LanguageConceptSwitch.SolutionReplacementStart:
        return myConceptSolutionReplacementStart;
      case LanguageConceptSwitch.SolutionStart:
        return myConceptSolutionStart;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCopyOption);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "File", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/6270343948071890297");
    b.version(3);
    b.property("extension", 0x15895b4d5040687dL).type(PrimitiveTypeId.STRING).origin("1551871934222854269").done();
    b.aggregate("fileComponents", 0x6ff78d4ba1740029L).target(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L).optional(true).ordered(true).multiple(true).origin("8068072613428330537").done();
    b.alias("file");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIFileComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "IFileComponent", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L);
    b.interface_();
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751707553554");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSolution() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "Solution", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L);
    b.class_(false, false, false);
    b.parent(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/7746099007950515107");
    b.version(3);
    b.property("taskNumber", 0x4e183cf3aedc858fL).type(PrimitiveTypeId.INTEGER).origin("5627314751707841935").done();
    b.property("copyOption", 0x4e183cf3aee61adeL).type(MetaIdFactory.dataTypeId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee61ad1L)).origin("5627314751708469982").done();
    b.associate("replacement", 0x4e183cf3aef7fa26L).target(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee80213L).optional(true).origin("5627314751709641254").done();
    b.aggregate("linesOfText", 0x4e183cf3aedc8595L).target(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL).optional(true).ordered(true).multiple(true).origin("5627314751707841941").done();
    b.alias("solution");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSolutionReplacement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "SolutionReplacement", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee80213L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708594707");
    b.version(3);
    b.property("id", 0x4e183cf3aee80214L).type(PrimitiveTypeId.INTEGER).origin("5627314751708594708").done();
    b.aggregate("linesOfText", 0x4e183cf3aee80216L).target(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL).optional(true).ordered(true).multiple(true).origin("5627314751708594710").done();
    b.alias("solutionReplacement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSolutionReplacementStart() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "SolutionReplacementStart", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee81512L);
    b.class_(false, false, false);
    b.parent(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751708599570");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSolutionStart() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "SolutionStart", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81d05L);
    b.class_(false, false, false);
    b.parent(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/5627314751707553029");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel", "Text", 0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL);
    b.class_(false, false, false);
    b.parent(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81f12L);
    b.origin("r:7d329b19-18b9-4029-9154-f8f288327b5e(Paastel.structure)/8068072613428330541");
    b.version(3);
    b.property("text", 0x6ff78d4ba174002eL).type(PrimitiveTypeId.STRING).origin("8068072613428330542").done();
    b.alias("text");
    return b.create();
  }
}
