package Paastel_V0.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int File = 0;
  public static final int Node = 1;
  public static final int Position = 2;
  public static final int Range = 3;
  public static final int Token = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L);
    builder.put(0x5704bc995c5738f1L, File);
    builder.put(0x6b7fac01d3d3ffb5L, Node);
    builder.put(0x5704bc995c586d99L, Position);
    builder.put(0x5704bc995c586d87L, Range);
    builder.put(0x6b7fac01d3d3ffb0L, Token);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
