package Paastel_V0.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFile = createDescriptorForFile();
  /*package*/ final ConceptDescriptor myConceptNode = createDescriptorForNode();
  /*package*/ final ConceptDescriptor myConceptPosition = createDescriptorForPosition();
  /*package*/ final ConceptDescriptor myConceptRange = createDescriptorForRange();
  /*package*/ final ConceptDescriptor myConceptToken = createDescriptorForToken();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFile, myConceptNode, myConceptPosition, myConceptRange, myConceptToken);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.File:
        return myConceptFile;
      case LanguageConceptSwitch.Node:
        return myConceptNode;
      case LanguageConceptSwitch.Position:
        return myConceptPosition;
      case LanguageConceptSwitch.Range:
        return myConceptRange;
      case LanguageConceptSwitch.Token:
        return myConceptToken;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel_V0", "File", 0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c5738f1L);
    b.class_(false, false, false);
    b.origin("r:11194643-bf9b-416e-bbf7-178d92cb9de8(Paastel_V0.structure)/6270343948071811313");
    b.version(3);
    b.property("name", 0x5704bc995c586d68L).type(PrimitiveTypeId.STRING).origin("6270343948071890280").done();
    b.aggregate("ast", 0x5704bc995c586d76L).target(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L).optional(true).ordered(true).multiple(false).origin("6270343948071890294").done();
    b.alias("file");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel_V0", "Node", 0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb5L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:11194643-bf9b-416e-bbf7-178d92cb9de8(Paastel_V0.structure)/7746099007949373365");
    b.version(3);
    b.associate("startToken", 0x6b7fac01d3d3ffb8L).target(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L).optional(true).origin("7746099007949373368").done();
    b.associate("endToken", 0x6b7fac01d3d3ffbaL).target(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L).optional(true).origin("7746099007949373370").done();
    b.alias("node2");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPosition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel_V0", "Position", 0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d99L);
    b.class_(false, false, false);
    b.origin("r:11194643-bf9b-416e-bbf7-178d92cb9de8(Paastel_V0.structure)/6270343948071890329");
    b.version(3);
    b.property("line", 0x5704bc995c586d9aL).type(PrimitiveTypeId.INTEGER).origin("6270343948071890330").done();
    b.property("column", 0x5704bc995c586d9cL).type(PrimitiveTypeId.INTEGER).origin("6270343948071890332").done();
    b.alias("position");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRange() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel_V0", "Range", 0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d87L);
    b.class_(false, false, false);
    b.origin("r:11194643-bf9b-416e-bbf7-178d92cb9de8(Paastel_V0.structure)/6270343948071890311");
    b.version(3);
    b.aggregate("startPosition", 0x5704bc995c586d91L).target(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d99L).optional(false).ordered(true).multiple(false).origin("6270343948071890321").done();
    b.aggregate("endPosition", 0x5704bc995c586d96L).target(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d99L).optional(false).ordered(true).multiple(false).origin("6270343948071890326").done();
    b.alias("range");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToken() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Paastel_V0", "Token", 0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L);
    b.class_(false, false, false);
    b.origin("r:11194643-bf9b-416e-bbf7-178d92cb9de8(Paastel_V0.structure)/7746099007949373360");
    b.version(3);
    b.property("text", 0x6b7fac01d3d3ffb1L).type(PrimitiveTypeId.STRING).origin("7746099007949373361").done();
    b.associate("next", 0x6b7fac01d3d3ffb3L).target(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L).optional(true).origin("7746099007949373363").done();
    b.alias("token");
    return b.create();
  }
}
