package Paastel.importer;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import java.io.IOException;
import jetbrains.mps.smodel.tempmodel.TemporaryModels;
import jetbrains.mps.smodel.tempmodel.TempModuleOptions;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import com.google.gson.JsonElement;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import com.google.gson.JsonParser;
import com.google.gson.JsonObject;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ImportLogicJson {

  public static void importData(String sourceFile, SModel targetModel) throws IOException {
    TemporaryModels temporaryModels = TemporaryModels.getInstance();
    SModel tempModel = temporaryModels.createReadOnly(TempModuleOptions.forDefaultModule());
    try {
      importDataIntoModel(sourceFile, tempModel);
      for (SNode sourceRoot : ListSequence.fromList(SModelOperations.roots(tempModel, CONCEPTS.File$Vm))) {
        SModelOperations.addRootNode(targetModel, sourceRoot);
      }
    } finally {
      temporaryModels.dispose(tempModel);
    }
  }

  private static void importDataIntoModel(String sourceFile, SModel targetModel) throws IOException {
    final JsonElement element;

    try (Reader reader = Files.newBufferedReader(Path.of(sourceFile))) {

      element = JsonParser.parseReader(reader);
    }

    JsonObject fileObject = element.getAsJsonObject();

  }



  private static final class CONCEPTS {
    /*package*/ static final SConcept File$Vm = MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, "Paastel.structure.File");
  }
}
