package Paastel.importer;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import java.io.IOException;
import jetbrains.mps.smodel.tempmodel.TemporaryModels;
import jetbrains.mps.smodel.tempmodel.TempModuleOptions;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Iterator;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ImportLogic {

  public static void importData(String sourceFile, SModel targetModel, int spacesInTabsAndIndent) throws IOException {
    TemporaryModels temporaryModels = TemporaryModels.getInstance();
    SModel tempModel = temporaryModels.createReadOnly(TempModuleOptions.forDefaultModule());
    try {
      importDataIntoModel(sourceFile, tempModel, spacesInTabsAndIndent);
      for (SNode sourceRoot : ListSequence.fromList(SModelOperations.roots(tempModel, CONCEPTS.File$Vm))) {
        SModelOperations.addRootNode(targetModel, sourceRoot);
      }
    } finally {
      temporaryModels.dispose(tempModel);
    }
  }

  private static void importDataIntoModel(String sourceFile, SModel targetModel, int spacesInTabsAndIndent) throws IOException {

    try (BufferedReader reader = Files.newBufferedReader(Path.of(sourceFile))) {
      SNode file = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, "Paastel.structure.File"));
      SPropertyOperations.assign(file, PROPS.name$MnvL, com.google.common.io.Files.getNameWithoutExtension(sourceFile));
      SPropertyOperations.assign(file, PROPS.extension$Y_Hs, com.google.common.io.Files.getFileExtension(sourceFile));
      Iterator<String> iterator = reader.lines().iterator();
      while (iterator.hasNext()) {
        SNode lineOfText = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL, "Paastel.structure.Text"));
        SPropertyOperations.assign(lineOfText, PROPS.text$f9B0, iterator.next().replaceAll("\t", " ".repeat(spacesInTabsAndIndent)));
        ListSequence.fromList(SLinkOperations.getChildren(file, LINKS.fileComponents$qwmK)).addElement(lineOfText);
      }
      SModelOperations.addRootNode(targetModel, file);
    }

  }



  private static final class CONCEPTS {
    /*package*/ static final SConcept File$Vm = MetaAdapterFactory.getConcept(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, "Paastel.structure.File");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty extension$Y_Hs = MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, 0x15895b4d5040687dL, "extension");
    /*package*/ static final SProperty text$f9B0 = MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL, 0x6ff78d4ba174002eL, "text");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink fileComponents$qwmK = MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L, 0x6ff78d4ba1740029L, "fileComponents");
  }
}
