package Paastel.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.cells.KeyMap;
import java.util.Arrays;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new File_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Solution_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new SolutionReplacement_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new SolutionReplacementStart_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new SolutionStart_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Text_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<KeyMap> getDeclaredKeyMaps() {
    return Arrays.<KeyMap>asList(new markText_KeyMap());
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d79L), MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3e56ba3L), MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee80213L), MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aee81512L), MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x4e183cf3aed81d05L), MetaIdFactory.conceptId(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6ff78d4ba174002dL)).seal();
}
