package Paastel.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.project.EditableFilteringScope;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.lang.migration.runtime.base.RefactoringRuntime;
import jetbrains.mps.lang.migration.runtime.base.Problem;
import jetbrains.mps.internal.collections.runtime.ISequenceClosure;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.closures.runtime.YieldingIterator;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.lang.migration.runtime.base.DeprecatedConceptNotMigratedProblem;
import jetbrains.mps.lang.migration.runtime.base.DeprecatedConceptMemberNotMigratedProblem;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class Migrate_MoveConcepts_0 extends MigrationScriptBase {
  private final String description = "Move 5 concepts to language `Paastel_V0`";
  public String getCaption() {
    return description;
  }
  @Override
  public boolean isRerunnable() {
    return true;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    {
      SearchScope scope_fkfbwg_a0e = CommandUtil.createScope(m);
      final SearchScope scope_fkfbwg_a0e_0 = new EditableFilteringScope(scope_fkfbwg_a0e);
      QueryExecutionContext context = new QueryExecutionContext() {
        public SearchScope getDefaultSearchScope() {
          return scope_fkfbwg_a0e_0;
        }
      };
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c5738f1L, "File_old")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb5L, "Node2_old")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d99L, "Position_old")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d87L, "Range_old")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb0L, "Token_old")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changePropertyInstance(node, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d68L, "name_old"), MetaAdapterFactory.getProperty(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c5738f1L, 0x5704bc995c586d68L, "name"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changePropertyInstance(node, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9aL, "line_old"), MetaAdapterFactory.getProperty(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d99L, 0x5704bc995c586d9aL, "line"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changePropertyInstance(node, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9cL, "column_old"), MetaAdapterFactory.getProperty(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d99L, 0x5704bc995c586d9cL, "column"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changePropertyInstance(node, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb1L, "text_old"), MetaAdapterFactory.getProperty(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb1L, "text"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d76L, "ast_old"), MetaAdapterFactory.getContainmentLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c5738f1L, 0x5704bc995c586d76L, "ast"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d91L, "startPosition_old"), MetaAdapterFactory.getContainmentLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d87L, 0x5704bc995c586d91L, "startPosition"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d96L, "endPosition_old"), MetaAdapterFactory.getContainmentLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x5704bc995c586d87L, 0x5704bc995c586d96L, "endPosition"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeReferenceLinkInstances(node, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffb8L, "startToken_old"), MetaAdapterFactory.getReferenceLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffb8L, "startToken"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeReferenceLinkInstances(node, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffbaL, "endToken_old"), MetaAdapterFactory.getReferenceLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffbaL, "endToken"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token"))) || Migrate_MoveConcepts_0.isMovedConcept(SNodeOperations.getConcept(it));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeReferenceLinkInstances(node, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb3L, "next_old"), MetaAdapterFactory.getReferenceLink(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb3L, "next"));
        }
      });
    }
  }
  @Override
  public Iterable<Problem> check(SModule m) {
    {
      SearchScope scope_fkfbwg_a0f = CommandUtil.createScope(m);
      final SearchScope scope_fkfbwg_a0f_0 = new EditableFilteringScope(scope_fkfbwg_a0f);
      final QueryExecutionContext context = new QueryExecutionContext() {
        public SearchScope getDefaultSearchScope() {
          return scope_fkfbwg_a0f_0;
        }
      };
      return Sequence.fromClosure(new ISequenceClosure<Problem>() {
        public Iterable<Problem> iterable() {
          return new Iterable<Problem>() {
            public Iterator<Problem> iterator() {
              return new YieldingIterator<Problem>() {
                private int __CP__ = 0;
                protected boolean moveToNext() {
__loop__:
                  do {
__switch__:
                    switch (this.__CP__) {
                      case -1:
                        assert false : "Internal error";
                        return false;
                      case 2:
                        this._2__yield_fkfbwg_a0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c5738f1L, "File_old"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 3:
                        if (!(this._2__yield_fkfbwg_a0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 5;
                          break;
                        }
                        this._2__yield_fkfbwg_a0a0d0a0f = this._2__yield_fkfbwg_a0a0d0a0f_it.next();
                        this.__CP__ = 4;
                        break;
                      case 5:
                        this._6__yield_fkfbwg_b0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb5L, "Node2_old"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 7:
                        if (!(this._6__yield_fkfbwg_b0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 9;
                          break;
                        }
                        this._6__yield_fkfbwg_b0a0d0a0f = this._6__yield_fkfbwg_b0a0d0a0f_it.next();
                        this.__CP__ = 8;
                        break;
                      case 9:
                        this._10__yield_fkfbwg_c0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d99L, "Position_old"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 11:
                        if (!(this._10__yield_fkfbwg_c0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 13;
                          break;
                        }
                        this._10__yield_fkfbwg_c0a0d0a0f = this._10__yield_fkfbwg_c0a0d0a0f_it.next();
                        this.__CP__ = 12;
                        break;
                      case 13:
                        this._14__yield_fkfbwg_d0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d87L, "Range_old"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 15:
                        if (!(this._14__yield_fkfbwg_d0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 17;
                          break;
                        }
                        this._14__yield_fkfbwg_d0a0d0a0f = this._14__yield_fkfbwg_d0a0d0a0f_it.next();
                        this.__CP__ = 16;
                        break;
                      case 17:
                        this._18__yield_fkfbwg_e0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb0L, "Token_old"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 19:
                        if (!(this._18__yield_fkfbwg_e0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 21;
                          break;
                        }
                        this._18__yield_fkfbwg_e0a0d0a0f = this._18__yield_fkfbwg_e0a0d0a0f_it.next();
                        this.__CP__ = 20;
                        break;
                      case 21:
                        this._22__yield_fkfbwg_f0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c5738f1L, "File_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.hasProperty(MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d68L, "name_old"));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedProperty(it, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d68L, "name_old"));
                          }
                        })).iterator();
                      case 23:
                        if (!(this._22__yield_fkfbwg_f0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 25;
                          break;
                        }
                        this._22__yield_fkfbwg_f0a0d0a0f = this._22__yield_fkfbwg_f0a0d0a0f_it.next();
                        this.__CP__ = 24;
                        break;
                      case 25:
                        this._26__yield_fkfbwg_g0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d99L, "Position_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.hasProperty(MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9aL, "line_old"));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedProperty(it, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9aL, "line_old"));
                          }
                        })).iterator();
                      case 27:
                        if (!(this._26__yield_fkfbwg_g0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 29;
                          break;
                        }
                        this._26__yield_fkfbwg_g0a0d0a0f = this._26__yield_fkfbwg_g0a0d0a0f_it.next();
                        this.__CP__ = 28;
                        break;
                      case 29:
                        this._30__yield_fkfbwg_h0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d99L, "Position_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d99L, "Position")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.hasProperty(MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9cL, "column_old"));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedProperty(it, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d99L, 0x5704bc995c586d9cL, "column_old"));
                          }
                        })).iterator();
                      case 31:
                        if (!(this._30__yield_fkfbwg_h0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 33;
                          break;
                        }
                        this._30__yield_fkfbwg_h0a0d0a0f = this._30__yield_fkfbwg_h0a0d0a0f_it.next();
                        this.__CP__ = 32;
                        break;
                      case 33:
                        this._34__yield_fkfbwg_i0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb0L, "Token_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.hasProperty(MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb1L, "text_old"));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedProperty(it, MetaAdapterFactory.getProperty(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb1L, "text_old"));
                          }
                        })).iterator();
                      case 35:
                        if (!(this._34__yield_fkfbwg_i0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 37;
                          break;
                        }
                        this._34__yield_fkfbwg_i0a0d0a0f = this._34__yield_fkfbwg_i0a0d0a0f_it.next();
                        this.__CP__ = 36;
                        break;
                      case 37:
                        this._38__yield_fkfbwg_j0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c5738f1L, "File_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c5738f1L, "File")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d76L, "ast_old")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c5738f1L, 0x5704bc995c586d76L, "ast_old"));
                          }
                        })).iterator();
                      case 39:
                        if (!(this._38__yield_fkfbwg_j0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 41;
                          break;
                        }
                        this._38__yield_fkfbwg_j0a0d0a0f = this._38__yield_fkfbwg_j0a0d0a0f_it.next();
                        this.__CP__ = 40;
                        break;
                      case 41:
                        this._42__yield_fkfbwg_k0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d87L, "Range_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d91L, "startPosition_old")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d91L, "startPosition_old"));
                          }
                        })).iterator();
                      case 43:
                        if (!(this._42__yield_fkfbwg_k0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 45;
                          break;
                        }
                        this._42__yield_fkfbwg_k0a0d0a0f = this._42__yield_fkfbwg_k0a0d0a0f_it.next();
                        this.__CP__ = 44;
                        break;
                      case 45:
                        this._46__yield_fkfbwg_l0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d87L, "Range_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x5704bc995c586d87L, "Range")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d96L, "endPosition_old")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x5704bc995c586d87L, 0x5704bc995c586d96L, "endPosition_old"));
                          }
                        })).iterator();
                      case 47:
                        if (!(this._46__yield_fkfbwg_l0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 49;
                          break;
                        }
                        this._46__yield_fkfbwg_l0a0d0a0f = this._46__yield_fkfbwg_l0a0d0a0f_it.next();
                        this.__CP__ = 48;
                        break;
                      case 49:
                        this._50__yield_fkfbwg_m0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb5L, "Node2_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getReference(MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffb8L, "startToken_old")) != null;
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedReferenceLink(it, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffb8L, "startToken_old"));
                          }
                        })).iterator();
                      case 51:
                        if (!(this._50__yield_fkfbwg_m0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 53;
                          break;
                        }
                        this._50__yield_fkfbwg_m0a0d0a0f = this._50__yield_fkfbwg_m0a0d0a0f_it.next();
                        this.__CP__ = 52;
                        break;
                      case 53:
                        this._54__yield_fkfbwg_n0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb5L, "Node2_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb5L, "Node2")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getReference(MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffbaL, "endToken_old")) != null;
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedReferenceLink(it, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb5L, 0x6b7fac01d3d3ffbaL, "endToken_old"));
                          }
                        })).iterator();
                      case 55:
                        if (!(this._54__yield_fkfbwg_n0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 57;
                          break;
                        }
                        this._54__yield_fkfbwg_n0a0d0a0f = this._54__yield_fkfbwg_n0a0d0a0f_it.next();
                        this.__CP__ = 56;
                        break;
                      case 57:
                        this._58__yield_fkfbwg_o0a0d0a0f_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.selectScope(null, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb0L, "Token_old"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x933c48bd50ac4324L, 0x84ebdd9a390948e2L, "Paastel_V0"), 0x6b7fac01d3d3ffb0L, "Token")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getReference(MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb3L, "next_old")) != null;
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedReferenceLink(it, MetaAdapterFactory.getReferenceLink(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, 0x6b7fac01d3d3ffb0L, 0x6b7fac01d3d3ffb3L, "next_old"));
                          }
                        })).iterator();
                      case 59:
                        if (!(this._58__yield_fkfbwg_o0a0d0a0f_it.hasNext())) {
                          this.__CP__ = 1;
                          break;
                        }
                        this._58__yield_fkfbwg_o0a0d0a0f = this._58__yield_fkfbwg_o0a0d0a0f_it.next();
                        this.__CP__ = 60;
                        break;
                      case 6:
                        this.__CP__ = 3;
                        this.yield(_2__yield_fkfbwg_a0a0d0a0f);
                        return true;
                      case 10:
                        this.__CP__ = 7;
                        this.yield(_6__yield_fkfbwg_b0a0d0a0f);
                        return true;
                      case 14:
                        this.__CP__ = 11;
                        this.yield(_10__yield_fkfbwg_c0a0d0a0f);
                        return true;
                      case 18:
                        this.__CP__ = 15;
                        this.yield(_14__yield_fkfbwg_d0a0d0a0f);
                        return true;
                      case 22:
                        this.__CP__ = 19;
                        this.yield(_18__yield_fkfbwg_e0a0d0a0f);
                        return true;
                      case 26:
                        this.__CP__ = 23;
                        this.yield(_22__yield_fkfbwg_f0a0d0a0f);
                        return true;
                      case 30:
                        this.__CP__ = 27;
                        this.yield(_26__yield_fkfbwg_g0a0d0a0f);
                        return true;
                      case 34:
                        this.__CP__ = 31;
                        this.yield(_30__yield_fkfbwg_h0a0d0a0f);
                        return true;
                      case 38:
                        this.__CP__ = 35;
                        this.yield(_34__yield_fkfbwg_i0a0d0a0f);
                        return true;
                      case 42:
                        this.__CP__ = 39;
                        this.yield(_38__yield_fkfbwg_j0a0d0a0f);
                        return true;
                      case 46:
                        this.__CP__ = 43;
                        this.yield(_42__yield_fkfbwg_k0a0d0a0f);
                        return true;
                      case 50:
                        this.__CP__ = 47;
                        this.yield(_46__yield_fkfbwg_l0a0d0a0f);
                        return true;
                      case 54:
                        this.__CP__ = 51;
                        this.yield(_50__yield_fkfbwg_m0a0d0a0f);
                        return true;
                      case 58:
                        this.__CP__ = 55;
                        this.yield(_54__yield_fkfbwg_n0a0d0a0f);
                        return true;
                      case 61:
                        this.__CP__ = 59;
                        this.yield(_58__yield_fkfbwg_o0a0d0a0f);
                        return true;
                      case 0:
                        this.__CP__ = 2;
                        break;
                      case 4:
                        this.__CP__ = 6;
                        break;
                      case 8:
                        this.__CP__ = 10;
                        break;
                      case 12:
                        this.__CP__ = 14;
                        break;
                      case 16:
                        this.__CP__ = 18;
                        break;
                      case 20:
                        this.__CP__ = 22;
                        break;
                      case 24:
                        this.__CP__ = 26;
                        break;
                      case 28:
                        this.__CP__ = 30;
                        break;
                      case 32:
                        this.__CP__ = 34;
                        break;
                      case 36:
                        this.__CP__ = 38;
                        break;
                      case 40:
                        this.__CP__ = 42;
                        break;
                      case 44:
                        this.__CP__ = 46;
                        break;
                      case 48:
                        this.__CP__ = 50;
                        break;
                      case 52:
                        this.__CP__ = 54;
                        break;
                      case 56:
                        this.__CP__ = 58;
                        break;
                      case 60:
                        this.__CP__ = 61;
                        break;
                      default:
                        break __loop__;
                    }
                  } while (true);
                  return false;
                }
                private Problem _2__yield_fkfbwg_a0a0d0a0f;
                private Iterator<Problem> _2__yield_fkfbwg_a0a0d0a0f_it;
                private Problem _6__yield_fkfbwg_b0a0d0a0f;
                private Iterator<Problem> _6__yield_fkfbwg_b0a0d0a0f_it;
                private Problem _10__yield_fkfbwg_c0a0d0a0f;
                private Iterator<Problem> _10__yield_fkfbwg_c0a0d0a0f_it;
                private Problem _14__yield_fkfbwg_d0a0d0a0f;
                private Iterator<Problem> _14__yield_fkfbwg_d0a0d0a0f_it;
                private Problem _18__yield_fkfbwg_e0a0d0a0f;
                private Iterator<Problem> _18__yield_fkfbwg_e0a0d0a0f_it;
                private Problem _22__yield_fkfbwg_f0a0d0a0f;
                private Iterator<Problem> _22__yield_fkfbwg_f0a0d0a0f_it;
                private Problem _26__yield_fkfbwg_g0a0d0a0f;
                private Iterator<Problem> _26__yield_fkfbwg_g0a0d0a0f_it;
                private Problem _30__yield_fkfbwg_h0a0d0a0f;
                private Iterator<Problem> _30__yield_fkfbwg_h0a0d0a0f_it;
                private Problem _34__yield_fkfbwg_i0a0d0a0f;
                private Iterator<Problem> _34__yield_fkfbwg_i0a0d0a0f_it;
                private Problem _38__yield_fkfbwg_j0a0d0a0f;
                private Iterator<Problem> _38__yield_fkfbwg_j0a0d0a0f_it;
                private Problem _42__yield_fkfbwg_k0a0d0a0f;
                private Iterator<Problem> _42__yield_fkfbwg_k0a0d0a0f_it;
                private Problem _46__yield_fkfbwg_l0a0d0a0f;
                private Iterator<Problem> _46__yield_fkfbwg_l0a0d0a0f_it;
                private Problem _50__yield_fkfbwg_m0a0d0a0f;
                private Iterator<Problem> _50__yield_fkfbwg_m0a0d0a0f_it;
                private Problem _54__yield_fkfbwg_n0a0d0a0f;
                private Iterator<Problem> _54__yield_fkfbwg_n0a0d0a0f_it;
                private Problem _58__yield_fkfbwg_o0a0d0a0f;
                private Iterator<Problem> _58__yield_fkfbwg_o0a0d0a0f_it;
              };
            }
          };
        }
      });
    }
  }
  public MigrationScriptReference getReference() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0);
  }
  public static boolean isMovedConcept(SAbstractConcept c) {
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c5738f1L, "File_old")))) {
      return true;
    }
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb5L, "Node2_old")))) {
      return true;
    }
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d99L, "Position_old")))) {
      return true;
    }
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x5704bc995c586d87L, "Range_old")))) {
      return true;
    }
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7c3f25f3e6f41a5L, 0xa4503772231a81bdL, "Paastel"), 0x6b7fac01d3d3ffb0L, "Token_old")))) {
      return true;
    }
    return false;
  }
}
