package file.importer.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptImportConfiguration = createDescriptorForImportConfiguration();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptImportConfiguration);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ImportConfiguration:
        return myConceptImportConfiguration;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForImportConfiguration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file.importer", "ImportConfiguration", 0x5273bfda51b4e42L, 0xaf350e5e0aa28effL, 0x21481ec840c64addL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:13fa9345-8f02-41e2-9a7d-a6e3ca63e656(file.importer.structure)/2398200647003818717");
    b.version(3);
    b.property("sourceFile", 0x21481ec840c64b2dL).type(PrimitiveTypeId.STRING).origin("2398200647003818797").done();
    b.property("spacesInTabAndIndent", 0x15895b4d5075d5b0L).type(PrimitiveTypeId.INTEGER).origin("1551871934226355632").done();
    b.alias("Import Configuration");
    return b.create();
  }
}
